language: python
python:
- '3.6'
install:
- pip install -r requirements.txt --quiet
- pip install pytest
- pip install pytest-cov
- pip install coverage
- pip install mkdocs
- pip install mkdocs-material
script:
- pytest tests --cov=autokeras --cov-report xml:coverage.xml
- sh docs.sh
after_success:
- pip install python-coveralls && coveralls
deploy:
- provider: pypi
  user: jhfjhfj1
  password:
    secure: U8U+CHDkQlCv6s0ZjbwAqW1RWxU8sV+EOeXVfCIOFJt9Igk16/Onoi8Bbdc52w3rPlgdtR78MxLgR6HsaVWSoZn0dardl6C/F3u+aGzh3dsQF2lfEH+Dl4Y+EasPmo4uKsH7rttT2kpn+w8zmL4IZz/W/ML1WkXv0Dhz6iH1uPS2dsC+uxdfz+W1iii/BACaPPzZdu79N+QBepRJs3VurXyB9UpV/FmsYSTB/2eP1yD/AzkV4RbhfSVRXDqIwvwpHOBqpY/4GJFONkC7oi7JtOMs/6ZjHw/2bpIziWPK1s7HbrYtqfs9w5RG279iwakU94O45xh2v73E++/oJtRqpFAGHAw0SNhm7dprSEU/EwJUaNKj2HGRmIQ2dvr56h3W1lsteS1GR9sNcHrR/AtA+sEiHDFUxlhALEVb9xI7Yk6Bl7/rpoqIBWKSyeu7LomGoCEs6ZE2ljPcRB8OIZSE7FzjiPpWfxabwPG84XufhR834z1C3qnepTkDDRYM/5M954lEbBp8eB8GJGj51DMNifXfHvtJosQPLChFrDrZlRYKLcvKuYASFeJc/v2+Q1p1vPyjHy1eMyM+bES57qBK1KbMVa+sY7dre26b0NMpcUpk6YczR7AIiD330ME7QHglJAHaacXUyBIfflRnPvmsAwB1HY0waH4/OvTFYMU+TLo=
  on:
    tags: true
    repo: jhfjhfj1/autokeras
- provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local-dir: docs/
  target-branch: gh-pages
  on:
    branch: master
env:
  global:
    secure: iiD1urajfg1L3LqDvKZmHfJrwlEGpFQzoDU3ZJdu11f9yJ68pyC2o1xu8eALdwirX91+nftfnmsJFsnXDF90RM1I90u/6Exl2/vWQXeCvIirFqe3IhbQB893lh8nCK/Yz5ZxPyII8oOEfpiiwWZJJlJL4ydKJtSsIhmH06t84EwygXbms+JN0vZvm5Ct6ap98pu4Kj7uGZYjxA9uFz37z1KL+ZGtthW7f8pVdKgsKxcqtn6qIg+y0o//A+MKitsy/oABd2oCbrUNoAEQtS02FN5+SMB1hN0s1RUHK00IE2c6yVS5qEzN4hFEkM7lvSPogxSkmZy51gwmDC8IGLjeCa4JSLS+a675XdXwiXAXHXbFm4+gSzd04CKcasdRLiB1ZzAH5VpCEGTTWeFOWWbg8UKmMo/jDzHCjPslWY2/wCOVyhIFCQ8Jbd8pnOTsXs9hhOEU/PwhlRIGiIJx6aQkd3XSq7Vb2ncGfYdFwfrLgCzDvO3ZULQPfVkynRTa0Ws4oErSQjRzS8EzLh5AMc+Pb4cRfPMz7zNr4bQ5UAAmNDCK+Pm964TxZcc48x4aDnpUqEDkNg/cu1W9Kn5fnYG+Txm0M1RrUp1ci0GRPxJtmAhZhVmFHDDmVTYswZq98zKrzNOaPArioPvR3jsfD7oc1Jd2nojcXHPSYLKAiv6Z3Ak=
