language: python
python:
- '3.6'
jobs:
  include:
    - stage: test
      script:
        - pip install -e .[tests] --progress-bar off
        - pip install git+git://github.com/keras-team/keras-tuner@master#egg=keras-tuner
        - pip install codacy-coverage
        - pytest tests --cov=autokeras --cov-report xml:coverage.xml
        - if [[ -z $CODACY_PROJECT_TOKEN ]]; then
            python-codacy-coverage -r coverage.xml;
          fi
    -
      script:
        - pip install -e .[tests] --progress-bar off
        - pip install git+git://github.com/keras-team/keras-tuner@master#egg=keras-tuner
        - flake8
    - stage: deploy
      script:
        - pip install -e .[tests] --progress-bar off
        - pip install git+git://github.com/keras-team/keras-tuner@master#egg=keras-tuner
        - pip install mkdocs
        - pip install mkdocs-material
        - sh shell/docs.sh
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: "$GITHUB_TOKEN"
          keep-history: true
          local-dir: docs/site
          target-branch: gh-pages
          on:
            branch: master
    -
      script:
        - python --version
      deploy:
      - provider: pypi
        user: jhfjhfj1
        password:
          secure: Lv2r6T1BKcL3RR0OzdFjJ3CFCLxHtwGxYeavtQK1KcixnFkVjuXC653RWhsllb03/j1uD48PIkV9Klc+tA5WspD/ptK1O6kLaeYCb2DmW6v0Qp0dZMDhsU/hIEdRspVAXkiBbsLTh/KKwnMWH8OArxkLeYQFQDHNGtt1H6yllcVy4JzxePLNOIXockwv+9WEUzWuLefExzkgrhdfrelSWclHMAgkqNI+2pcPKAMsXaz/TdhfYL0ofo13G6J4e34IaTUSJJ4eMOg9vBFx/9Z5shpSRdpDjwnIkJIS51IVAP2EetK5Yyr5rhJDy3vrObs6R94GG+zZB+gRWXfIZ8oUL3Y18aHdQR/roRJ+k29D2WLIR9JZ9Y08GRQ5rewpzyJ5hvZEaDONzZ+j7Vhe4mQa5Eo3DDLROFQryP78aw5dYAw6mXXbn7jd5Yf3Z+K1p3dsS32hicbiINjjPwgqzfFwTXLmj/kETdRQqrXlxkCdyE0YjfJGrOhRNTEY/NWQ/siG/mvo7J6dEamhFF7O6s95D4SZmhH7wpVuIy9jh/0zrLH5CAS7a39PXGWGqIDdaImgFXNDps1xpwRA2A8gDoWEvksE+B1AVzUFvqBxHWYBBQpCAMduN25ML2y2gTc6Cv/CA9sntHzB9D6nT7WMVeZexPJhpQfE+38IFUdW6eqkdd8=
        on:
          tags: true
          repo: keras-team/autokeras
env:
  global:
    secure: hukof0dDtKZsiD6f7t2KFuJJlX53HRZ9w54EdDod6/JpLaRNP6pHp7zNdxmwZREfZXFQgq2UxaY4vUM5vw6xHoaF0OrOaqU+dUdQxei5q/RBZCcrSaabGaztXm0zDookRSQtuo3w7g6/3mbBguMhRge1h9u021iZ5Hxdams6bDcCeK7M+2+utoB8nUI7otiwzighvuV3/8cBGHdyKHMuYs+lfQAingEGiT7PzRltoWHX1Qlw/78HURiQbcD01BpRQkzzgsznBZhlTdlWdWA2UGqhe7xu+ntg3w4+rHNIuQ0+FD0E3oRuiysKA1aZ7pDz9FlYDjx0WP4AFm6hbLBcVeJ02w7/6xAeMC8TJumrqxEDzWDas+Ybj8vS5daV2XrCvEH23+HnPnj9HGDkjhDFaIiJwFxfG5hYSZsQQnn09Bw0JnG8Qm0ytf3c+Z2ldtdD15iSlold0sE5i4YIWSkINm5WKP6nySpWfo9/S5v9rE+8sjNmua82bK010Hy6nZai/WRZgtJPRel0u0kl96FVaj7VPAaK8LqseBSoFCfUQQdtUNVPVchgWME060Pr2RHRLUfs/vXUlURU9mW9SpZFV2hMJCiuDaq7CGcY6lbmqZki7QFsY07c9yH8X8fGRn1y48UeDM7gEpnGmVCLnOD6SLoGFaulZHMdgaVX5ey/BAE=
