site_name: AutoKeras
theme:
  favicon: '/img/favicon.png'
  logo: '/img/logo_white.svg'
  name: 'material'
  palette:
    primary: 'red'
    accent: 'red'

docs_dir: sources
repo_url: https://github.com/keras-team/autokeras
site_url: http://autokeras.com
edit_uri: ""
site_description: 'Documentation for AutoKeras.'
google_analytics: ['UA-44322747-3', 'autokeras.com']

nav:
    - Home: index.md
    - Getting Started 1.0:
        - Overview: tutorial.md
        - Image Classification: tutorial.md
        - Image Regression: tutorial.md
        - Text Classification: tutorial.md
        - Text Regression: tutorial.md
        - Structured Data Classification: tutorial.md
        - Structured Data Regression: tutorial.md
        - Multi-Modal and Multi-Task: tutorial.md
        - Customized Model: tutorial.md
    - Getting Started 0.4: start.md
    - Docker: docker.md
    - Contributing Guide: contributing.md
    - Documentation:
      - Task APIs:
        - ImageClassifier: image_classifier.md
        - ImageRegressor: image_regressor.md
        - TextClassifier: text_classifier.md
        - TextRegressor: text_regressor.md
        - StructuredDataClassifier: structured_data_classifier.md
        - StructuredDataRegressor: structured_data_regressor.md
      - AutoModel: auto_model.md
      - Building Blocks:
        - Node: node.md
        - Preprocessor: preprocessor.md
        - Block: block.md
        - Head: head.md
    - About: about.md
