site_name: Auto-Keras
repo_url: https://github.com/jhfjhfj1/autokeras
site_url: http://autokeras.com
edit_uri: https://github.com/jhfjhfj1/autokeras/blob/master/mkdocs/docs/

pages:
    - Home: index.md
    - Documentation:
      - classifier: classifier.md
      - search: search.md
      - graph: graph.md
      - preprocessor: preprocessor.md
      - utils: utils.md
      - generator: generator.md
    - About: about.md
theme: readthedocs
