site_name: Auto-Keras
theme:
  name: 'material'
  palette:
    primary: 'teal'
    accent: 'teal'
repo_url: https://github.com/jhfjhfj1/autokeras
site_url: http://autokeras.com
edit_uri: ""
google_analytics: ['UA-44322747-3', 'autokeras.com']

nav:
    - Home: index.md
    - Getting Started: start.md
    - Docker: docker.md
    - Contributing Guide: temp/contribute.md
    - Neural Architecture Search: temp/nas.md
    - Documentation:
      - supervised: temp/supervised.md
      - image_supervised: temp/image_supervised.md
      - bayesian: temp/bayesian.md
      - search: temp/search.md
      - graph: temp/graph.md
      - preprocessor: temp/preprocessor.md
      - model_trainer: temp/model_trainer.md
      - utils: temp/utils.md
      - generator: temp/generator.md
    - About: about.md
